language: groovy

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

before_install:
  chmod +x gradlew

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# There is a 'testAll' task on the root project that essentially performs all of the steps in "install" and "script".
# However, we can't use it because the root GradleBuild doesn't propagate its properties to the child GradleBuilds
# that the task spawns, and the integration tests really need "geckoPlatform".

install: ./gradlew --info --stacktrace build

script:
  - cd integrationTests/
  # The default value of geckoPlatform is "macos". Obviously that won't work on Travis's Ubuntu VMs.
  - ./gradlew --info --stacktrace -PgeckoPlatform=linux64 testAll

env:
  global:
    - JAVA_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1G"
    # This is the value of my BINTRAY_KEY, encrypted.
    - secure: "pC+rLP05t/uyh0fqkty0RhX7FyPYIDFucZdMR8H9+j0l0FgsACA3epbUzCUkh3mvOM63oLQpqRcRkW1jmRjNiaAKgB2cpC1g0zKxLV9GTKUi2IK6n90f4GcNy14egkUb6Ko3AGOUtKJK/3BhZv+GEP3NmqEewTnWGCStPe9aEtzgGbeQjFNZb1b0qGKu7f69Co4loIKzzdpMAjt2/TmVHeFpRIr0Waz1+MrSDbsc8mszplIkG7u7ANCSLqfKhMwlVwHCrYUejExUOj/aqxfhPsuQ3qR+dm8XATQtyIJ825SmJIjDiq3hRDuaL/Pg4EQitB7aFSisKthdy1Mm9RpApMq7iFiicXRnv2tCw6U3JIj7D7L0GADkSRvoKqBcKYfdqXO/cTMUbYWOrVDVPP8LLCFj8qkdnPZ/2ATkeORyrS6/Y56v4qOVvFesjbw2/bv9La4a1MpYvRSx2d3otuJT1Q3rbbRexRz+mOQqFTnfPYOFDeYKYRsY848eWTGLJmMd487NG3fdHrfVWack5rt7NzW7ldJGg4IjPGojmvXaHMPKkLZ6/4WWpvMvxYCy+jzCMwvIRjDZh7fZK7nDiNYxPdfFiap57Pje0QURfixImg/eJU4x1rnXfQ3e/EKvaOr/42dsbf/mVEwxJBY2flZ2LHBk/HLYJXwACuZLNMkiMr4="

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload -PbintrayUser=cwardgar -PbintrayKey=${BINTRAY_KEY}
    on:
      tags: true
      jdk: oraclejdk8
